# Generated by Django 2.2.4 on 2020-05-24 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(max_length=1000)),
                ('food_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=1000)),
                ('fiber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamin_a', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamin_b6', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamin_b9', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamin_b12', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamin_c', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamin_d', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vitamin_e', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calcium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('omega_3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Food', to='crm.Entry')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('entryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Day', to='crm.Entry')),
            ],
        ),
    ]
