# Generated by Django 2.2.4 on 2020-05-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='food_weight',
        ),
    ]
