# Generated by Django 2.2.4 on 2020-05-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20200523_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='weight',
        ),
        migrations.AddField(
            model_name='food',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
