# Generated by Django 2.2.4 on 2020-05-24 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200523_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
